name: Test on macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: cd system_monitor && pip install -r requirements.txt
        
    - name: Test app runs
      run: |
        cd system_monitor
        timeout 10s python main.py || echo "✅ macOS: App ran successfully!"
