name: Test on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: cd system_monitor && pip install -r requirements.txt
        
    - name: Test app runs  
      run: |
        cd system_monitor
        Start-Process python -ArgumentList "main.py" -PassThru | Wait-Process -Timeout 10 -ErrorAction SilentlyContinue
        echo "✅ Windows: App ran successfully!"